name: cytodoro
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  lottie: ^3.3.1
  flutter_svg: ^1.0.0
  assets_audio_player: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assetss/animations/cell.json
    - assetss/animations/cellwiggle.json
    - assetss/animations/homescreen.png
    - assetss/animations/cytodoro.png
    - assetss/animations/start_button.svg
    - assetss/animations/Tap.mp3